/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _gosscreen1_h_
#define _gosscreen1_h_
//---------------------------------------------------------------------------------
extern const unsigned char gosscreen1[];
extern const int gosscreen1_size;
//---------------------------------------------------------------------------------
#endif //_gosscreen1_h_
//---------------------------------------------------------------------------------
